apiVersion: v1
kind: Deployment
metadata:
  name: k2view-agent
  labels:
    app: k2view-agent
spec:
    replicas: 1
    selector:
        matchLabels:
        app: k2view-agent
    template:
        metadata:
        labels:
            app: k2view-agent
        spec:
        containers:
        - name: k2view-agent
          image: gcr.io/k2view-rnd/fabric/k2view/k2v-agent:0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: K2VIEW_AGENT_CONFIG
